#!/bin/bash

# This script is to enable a second monitor (extended) in DWM

monitor=$(xrandr | grep " connected" | awk '{ print $1 }' | grep -v LVDS)

xrandr --output LVDS1 --mode 1366x768 --panning 1366x768 --output $monitor --auto --right-of LVDS1

feh  --bg-max --randomize ~/Pictures/spacefotes/screensavers/*

