#!/bin/bash

outputflag=0
flag=0

for file in "$@"; do
	echo $file
	if [[ "$file" = *[[:space:]]* ]]; then
		quote="\""
		file="$quote$file$quote"
	fi
	if [ "$flag" = 1 ]; then
		outputfile=$file
		flag=0
	else
		inputfile=${inputfile}" "${file}
	fi
	if [ "$file" = "-o" ]; then
		flag=1
		outputflag=1
	fi
done
if [ "$outputflag" = 0 ]; then
	echo "output file not defined, merged file is output.pdf"
	outputfile="output.pdf"
fi
eval gs -dNOPAUSE -dAutoRotatePages=/None -sDEVICE=pdfwrite -sOUTPUTFILE=$outputfile -dBATCH $inputfile



