#!/bin/bash

# This script is to disable a monitor / return to just laptop screen

monitor=$(xrandr | grep " connected" | awk '{ print $1 }' | grep -v LVDS)

xrandr --output LVDS1 --primary --mode 1366x768 --output $monitor --off

#current_res=$(xrandr | grep LVDS | awk '{ print $4 }')

#if [ "$current_res" != "1366x768+0+0" ]
#then
#	xrandr -s 1366x768
#fi
